### ISSUE TITLE
Fitbit.download.recipe fails to find a match on https://www.fitbit.com/setup

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/hansen-m-recipes#177]
The URL https://www.fitbit.com/setup now 404's but is still linked from other areas on the FitBit webpage so looks like an issue with the vender.

```
URLTextSearcher
{'Input': {'re_pattern': '(?P<url>https:\\/\\/cache\\.fitbit\\.com\\/FitbitConnect\\/FitbitConnect-v(?P<version>[0-9.]+)-(?P<release_date>[0-9-]+)\\.dmg)',
           'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
                                             'Mac OS X 10_10_4) '
                                             'AppleWebKit/600.7.12 (KHTML, '
                                             'like Gecko) Version/8.0.7 '
                                             'Safari/600.7.12'},
           'url': 'https://www.fitbit.com/setup'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 483, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.fitbit.com/setup
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
No match found on URL: https://www.fitbit.com/setup
Failed.
```

Tweeted at their support (https://twitter.com/Daz_Wallace/status/1323623205802811393?s=20) but I'd say this issue is the Vender's to fix and more of an FYI

**Comment by rustymyers** [comment]
This appears to be working for me, they must have fixed it. Thanks for the note!
